### ISSUE TITLE
Incomplete without Android

### ISSUE THREAD

**Issue by m-j-g** [tomgilder/flutter_sign_in_with_apple#9] opened 2019-11-19 17:36 UTC
You can't offer apple sign in only on iOS, because people switch from iPhones to Android over the years.  So, it's mandatory that your Android apps implement Apple Sign in.  And since this is a plugin for flutter, its quite anti-flutter and incomplete to only add the logic for iOS.

In order to be the community adopted library for apple sign in, it's going to have to support Android.  The logic for doing so is already done here: https://github.com/willowtreeapps/sign-in-with-apple-button-android .  

I'm not sure if it's easiest to add it to this one, or to create new flutter plugin that has the complete solution.

**Comment by Ahmadre** [comment] 2019-12-03 10:19
Guys more important: why isn't there a firebase compatible version?

**Comment by tomgilder** [comment] 2019-12-07 14:12
Closing, duplicate of https://github.com/tomgilder/flutter_apple_sign_in/issues/2

**Closed as completed by tomgilder** 2019-12-07 14:12 UTC
