### ISSUE TITLE
Unable to run the project in android .

### ISSUE THREAD

**Issue by VikashIOS** [tomgilder/flutter_sign_in_with_apple#27] opened 2020-01-22 07:11 UTC
* What went wrong:
A problem occurred configuring root project 'apple_sign_in'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
Please provide any solution I am stuck in the live project.

**Comment by tomgilder** [comment] 2020-04-10 16:04
Closing: duplicate of #26

**Closed as completed by tomgilder** 2020-04-10 16:04 UTC
